name: Publish Docker Image
on: [push]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-push-docker-image:
    if: github.ref == 'refs/heads/main'
    name: Build ${{ matrix.arch }} Image
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            name: amd64
          # - arch: arm64
          #   name: arm64

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout base
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get commit SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      # - name: Cache Docker layers
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ github.ref }}-${{ matrix.arch }}
      #     restore-keys: |
      #       ${{ github.ref }}-${{ matrix.arch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/${{ matrix.arch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,prefix=${{ matrix.arch }}-
            type=raw,value=latest

      - name: Copy
        run: |
          cp ./docker/* ./

      - name: Build and export
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/${{ matrix.arch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SHA=${{ steps.vars.outputs.sha_short }}
            GPTQ_FOR_LLAMA_VER=${{ vars.GPTQ_FOR_LLAMA_VER }}
            TORCH_CUDA_ARCH_LIST=${{ vars.TORCH_CUDA_ARCH_LIST }}
            WEBUI_VERSION=${{ steps.vars.outputs.sha_short }}
          outputs: type=image,push=true
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache
